# Generated by Django 3.2 on 2021-05-01 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApp', '0002_remove_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='total_price',
        ),
    ]
